<MenuScreen>:
    FloatLayout:
        id: layout_menu

        Image:
            id: image_logo
            source: "static/images/logo.png"
            size_hint_y: .15
            pos_hint: {"center_x": .5, "center_y": .75}
            allow_stretch: True

        Button:
            id: button_quit
            text: "QUIT"
            size_hint_y: .15
            pos_hint: {"center_x": .5, "center_y": .25}
            on_release: root.on_quit()